# Generated by Django 6.0.6 on 2026-07-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_customer_phone_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.CharField(blank=True, default='October 2027', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacture_date',
            field=models.CharField(blank=True, default='October 2025', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.TextField(blank=True, default='Fit-Hit Nutrition Labs Inc., Plot 42, Industrial Area, Phase-1, Chandigarh, India', null=True),
        ),
    ]
