# Generated by Django 6.0.6 on 2026-07-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_product_expiry_date_product_manufacture_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.TextField(blank=True, help_text='Separate with newlines', null=True),
        ),
    ]
